### ISSUE TITLE
add current line-ending status #enhancement

### ISSUE THREAD

**Issue by esterp** [williampuk/line-ending-converter#3]
Just like the 'UTF-8' that is on the status bar the line-ending of the current file could be displayed for information purposes.

**Comment by posita** [comment]
Emacs does this, and it's helpful:

![Uploading Screen Shot 2015-04-21 at 22.24.16.png . . .]()

If I may also suggest to also check (or disable) the currently detected status in any context menu. Something like:

![Uploading Screen Shot 2015-04-21 at 22.27.46.png . . .]()

**Comment by williampuk** [comment]
I also noticed that Notepad++ does both of these as well.
Displaying the status is useful to some, but a setting to enable/disable this will also need to be implemented as well. (Some people, like me, may already be satisfied with have the hidden character (LF/CR) shown.) 
For the context menu, I don't know how to programmatically change the option.

**Comment by posita** [comment]
I was kind of hoping `atom.menu` was mod-on-write-friendly, but it doesn't look like it is:

![obj_hierarchy.png](https://s3.amazonaws.com/uploads.hipchat.com/126832/920830/lVdGuLlb2v3r6bW/obj_hierarchy.png)

![mod_label.png](https://s3.amazonaws.com/uploads.hipchat.com/126832/920830/u6H8yD5qad5feU0/mod_label.png)

Mod'ing that structure doesn't seem to (alone) modify the menu: :disappointed:

![no_dice.png](https://s3.amazonaws.com/uploads.hipchat.com/126832/920830/u6vLl4TxVlkStXn/no_dice.png)

Although I don't suppose I should be surprised by that. :confused:

**Comment by posita** [comment]
UPDATE: [`Atom::menu`](https://atom.io/docs/api/v0.194.0/Atom#instance-menu) -> [`update()`](https://atom.io/docs/api/v0.194.0/MenuManager#instance-update) is probably what I was looking for (although this whole thing feels like a total hack to me):

![screen shot 2015-04-22 at 19 20 52](https://cloud.githubusercontent.com/assets/222581/7289420/b9e82026-e924-11e4-9fcf-dc2a7280d211.png)

![screen shot 2015-04-22 at 19 19 48](https://cloud.githubusercontent.com/assets/222581/7289418/a899164a-e924-11e4-88e8-a0d9bdcca0c7.png)

**Comment by williampuk** [comment]
This is now available in version 1.2.0.
Showing line endings conversion selection by clicking the status bar may also be implemented in the future, but this is out of the scope of this issue.

**Comment by posita** [comment]
To be clear (for those who might come in later who might be confused by my earlier comments/proposed screenshots), the fix was adding the current format to the status bar, correct?

![screen shot 2015-07-16 at 12 07 24](https://cloud.githubusercontent.com/assets/222581/8732596/62d3b756-2bb3-11e5-81fb-47ba1f8487f4.png)

**Comment by williampuk** [comment]
Yes, as the title of this issue suggests.
