### ISSUE TITLE
Works on linux, not on windows

### ISSUE THREAD

**Issue by Gibbz** [williampuk/line-ending-converter#8]
This plugin is great, except on my windows machine its not working at all :(

**Comment by williampuk** [comment]
What do you mean by not working at all? Do you have any use cases that the plugin is not working? I have tested it on Windows 10 and it is working properly.

**Comment by Gibbz** [comment]
hrmm, looks like its working now, just needed to reboot my machine!

**Comment by williampuk** [comment]
good
